version: '3.8'

services:
  roopapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - roop-data:/roop
    ports:
      - 8000:8000

volumes:
  roop-data: