version: '3.8'

services:
  roop-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - roop-data:/roop
    ports:
      - 8000:8000

volumes:
  roop-data: