version: '3.9'

services:
  roopapi:
    build:
      context: .
      dockerfile: cuda.Dockerfile
    restart: unless-stopped
    volumes:
      - roop-data:/roop
      - open-nsfw:/root/.opennsfw2
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  roop-data:
  open-nsfw: